#!/bin/bash

search_dir="../Datasets/cleaned"
for entry in "${search_dir}"/*.csv
do
  csv_name=${entry##*/}
  folder_name=${csv_name%.*}
  python visualiser.py -f $entry -n -i -b -o "out/$folder_name/"
done
