#!/bin/bash

search_dir="../../../dataset/cleaned"
for entry in "${search_dir}"/*.csv
do
  csv_name=${entry##*/}
  folder_name=${csv_name%.*}
  python rnn_classifier.py -f $entry -o "out/$folder_name/"
done
